assetDir = "static"
baseURL = "http://example.org/"
languageCode = "de-de"
pluralizelisttitles = false
title = "My New Hugo Site"
[[menu.mainmenu]]
identifier = "healingMethods"
name = "Heilverfahren"
weight = 9
