assetDir = "static"
baseURL = "http://example.org/"
languageCode = "de-de"
pluralizelisttitles = false
title = "My New Hugo Site"
[[menu.mainmenu]]
name = "Heilverfahren"
identifier = "healingMethods"
weight = 3
